version: '3.8'

networks:
  arch-network:
    driver: bridge

services:
  db: 
    image: postgres
    container_name: postgres-container
    restart: always
    networks:
      - arch-network
    environment:  
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 20s
      retries: 5
      start_period: 80s  
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
  teacher-api: 
    build: ./teacher
    container_name: teacher-node
    depends_on:
      db:
        condition: service_healthy
    networks:
      - arch-network
    env_file: ./teacher/.env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "3000:3000"
  student-api:
    build: ./student
    container_name: student-node
    depends_on:
      db:
        condition: service_healthy
    networks:
      - arch-network
    env_file: ./student/.env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "8080:8080"