version: '3.8'

networks:
  arch-network:
    driver: bridge

services:
  db: 
    image: postgres
    container_name: postgres-container
    restart: always
    networks:
      - arch-network
    environment:  
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
  teacher-api: 
    build: ./teacher
    container_name: teacher-node
    depends_on:
      db:
        condition: service_started
    networks:
      - arch-network
    env_file: ./teacher/.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
  student-api:
    build: ./student
    container_name: student-node
    depends_on:
      db:
        condition: service_started
    networks:
      - arch-network
    env_file: ./student/.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}